### PR TITLE
tweak to work with webpack/riot setup

### PR DESCRIPTION
**Pull request by casmit**

### CODE REVIEW

**Comment by adrian-enspired** [comment]
We're quite a ways behind upstream. We're not actually ahead of them (our "6 ahead" are all merge commits, and some of my PRs were split up differently here vs. upstream, but same changes) so upgrading should not be problematic.

Current upstream doesn't have this exact change, but it does seem people are using it with webpack, so might just work. if it doesn't, i'd be happier applying this change to the current release than on what we have here.

thoughts?

**Comment by casmit** [comment]
I tried using what we had with it because I thought there was something special you had done with the nocworx version for selectr. This was the only way I could get what we had with our frontend side selectr stuff to work, but I can give upstream a try.

**Comment by adrian-enspired** [comment]
There was a period of time where that was true, but all upstream PRs have long since been merged

If there are weird problems with upstream I'd say going ahead with this PR is OK

**Comment by casmit** [comment]
Latest version of upstream appears to work, this repo may no longer be needed.

**Pull request closed without merging**
